package net.mediaarea.mediainfo.demo

import android.content.Context
import android.graphics.Typeface
import android.text.SpannableStringBuilder
import android.text.Spanned
import android.text.style.ForegroundColorSpan
import android.text.style.StyleSpan
import android.text.style.RelativeSizeSpan
import androidx.core.content.ContextCompat

object MediaInfoTableRenderer {
    
    /**
     * Renderiza MediaInfo en formato tabla similar a la imagen de referencia
     */
    fun parseAndFormatAsTable(
        context: Context,
        output: String,
        isDarkTheme: Boolean,
        trimSpaces: Boolean = false
    ): CharSequence {
        if (output.isEmpty()) return ""
        
        val lines = output.lines()
        val builder = SpannableStringBuilder()
        
        // Colores según el tema
        val sectionColor = if (isDarkTheme) {
            ContextCompat.getColor(context, android.R.color.holo_orange_light)
        } else {
            ContextCompat.getColor(context, android.R.color.holo_orange_dark)
        }
        
        val labelColor = if (isDarkTheme) {
            ContextCompat.getColor(context, R.color.theme_dark_text_label)
        } else {
            ContextCompat.getColor(context, R.color.theme_default_text_label)
        }
        
        val valueColor = if (isDarkTheme) {
            ContextCompat.getColor(context, R.color.theme_dark_text_primary)
        } else {
            ContextCompat.getColor(context, R.color.theme_default_text_primary)
        }
        
        // Ancho máximo para las etiquetas (para alineación)
        val maxLabelWidth = 25
        
        for (line in lines) {
            val trimmed = line.trim()
            
            // Skip empty lines, headers, footers
            if (trimmed.isEmpty() || 
                trimmed.startsWith("=") || 
                trimmed.contains("MEDIA INFO") ||
                trimmed.contains("Generated by")) {
                continue
            }
            
            // Detectar secciones (General, Video, Audio, Text, etc.)
            if (trimmed.matches(Regex("^(General|Video|Audio|Text|Image|Menu|Other)(\\s+#\\d+)?$"))) {
                // Nueva sección con espacio superior
                if (builder.isNotEmpty()) {
                    builder.append("\n")
                }
                
                val start = builder.length
                builder.append(trimmed)
                builder.append("\n")
                
                // Estilo de sección: Bold + Color + Tamaño ligeramente mayor
                builder.setSpan(
                    StyleSpan(Typeface.BOLD),
                    start,
                    start + trimmed.length,
                    Spanned.SPAN_EXCLUSIVE_EXCLUSIVE
                )
                builder.setSpan(
                    ForegroundColorSpan(sectionColor),
                    start,
                    start + trimmed.length,
                    Spanned.SPAN_EXCLUSIVE_EXCLUSIVE
                )
                builder.setSpan(
                    RelativeSizeSpan(1.15f),
                    start,
                    start + trimmed.length,
                    Spanned.SPAN_EXCLUSIVE_EXCLUSIVE
                )
                
                builder.append("\n")
                continue
            }
            
            // Parsear líneas con formato "Label : Value"
            val colonIndex = trimmed.indexOf(':')
            if (colonIndex > 0) {
                val label = trimmed.substring(0, colonIndex).trim()
                val value = trimmed.substring(colonIndex + 1).trim()
                
                if (label.isNotEmpty() && value.isNotEmpty()) {
                    // Label (etiqueta a la izquierda)
                    val labelStart = builder.length
                    val paddedLabel = if (trimSpaces) {
                        label
                    } else {
                        label.padEnd(maxLabelWidth)
                    }
                    builder.append(paddedLabel)
                    
                    builder.setSpan(
                        ForegroundColorSpan(labelColor),
                        labelStart,
                        builder.length,
                        Spanned.SPAN_EXCLUSIVE_EXCLUSIVE
                    )
                    
                    // Espaciado entre columnas
                    builder.append("  ")
                    
                    // Value (valor a la derecha)
                    val valueStart = builder.length
                    builder.append(value)
                    builder.setSpan(
                        ForegroundColorSpan(valueColor),
                        valueStart,
                        builder.length,
                        Spanned.SPAN_EXCLUSIVE_EXCLUSIVE
                    )
                    
                    builder.append("\n")
                }
            } else if (trimmed.isNotEmpty() && !trimmed.startsWith("<") && !trimmed.startsWith("<!")) {
                // Línea sin formato especial
                val start = builder.length
                builder.append(trimmed)
                builder.setSpan(
                    ForegroundColorSpan(valueColor),
                    start,
                    builder.length,
                    Spanned.SPAN_EXCLUSIVE_EXCLUSIVE
                )
                builder.append("\n")
            }
        }
        
        return builder
    }
    
    /**
     * Calcula el ancho máximo de las etiquetas para mejor alineación
     */
    private fun calculateMaxLabelWidth(lines: List<String>): Int {
        var maxWidth = 0
        for (line in lines) {
            val colonIndex = line.indexOf(':')
            if (colonIndex > 0) {
                val label = line.substring(0, colonIndex).trim()
                if (label.length > maxWidth) {
                    maxWidth = label.length
                }
            }
        }
        return minOf(maxWidth, 30) // Limitar a 30 caracteres máximo
    }
}
